trigger:
  branches:
    include:
      - main

stages:
- stage: Deploy_DEV
  displayName: 'Deploy to DEV Environment'
  jobs:
  - deployment: DeployAutomationAccount
    displayName: 'Deploy Automation Account'
    environment: DEV
    strategy:
      runOnce:
        deploy:
          steps:
          - template: azure-cli-deploy.yml
            parameters:
              environment: 'DEV'

- stage: Deploy_UAT
  displayName: 'Deploy to UAT Environment'
  dependsOn: Deploy_DEV
  condition: succeeded()
  jobs:
  - deployment: DeployAutomationAccount
    displayName: 'Deploy Automation Account'
    environment: UAT
    strategy:
      runOnce:
        deploy:
          steps:
          - template: azure-cli-deploy.yml
            parameters:
              environment: 'UAT'

- stage: Deploy_PROD
  displayName: 'Deploy to PROD Environment'
  dependsOn: Deploy_UAT
  condition: succeeded()
  jobs:
  - deployment: DeployAutomationAccount
    displayName: 'Deploy Automation Account'
    environment:  PROD
    strategy:
      runOnce:
        deploy:
          steps:
          - template: azure-cli-deploy.yml
            parameters:
              environment: 'PROD'
